class RedisKey:
    ALGO_STALKER_DATA = 'stalker-data'
    EXCHANGE_WALLET = 'exchange-wallet'
    MARGIN_WALLET = 'margin-wallet'
    ORDERBOOK_UPDATES = 'orderbook-updates'
    RESTING_ORDERS = 'resting-orders'
    STALKER_SYMBOLS = 'stalker-symbols'
    STALKER_SYMBOLS_SUBBED = 'stalker-symbols-subbed'
    STALKER_ORDERS = 'stalker-orders'
    SYMBOLS_EXCLUDED = 'symbols-excluded'
    SYMBOLS_INCLUDED = 'symbols-included'
    SYMBOLS_SUBBED_BFX = 'bfx-symbols-subbed'
    SYMBOLS_TO_SUB_BFX = 'bfx-symbols-to-sub'
