apiVersion: apps/v1
kind: Deployment
metadata:
  name: bellagio
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bellagio
  template:
    metadata:
      labels:
        component: bellagio
    spec:
      containers:
        - name: bellagio
          image: matthewli1409/bfx-bellagio
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          env:
            - name: FUND_NAME
              value: "BFX_FEE"
          envFrom:
            - secretRef:
                name: credentials
            - configMapRef:
                name: env-config
      imagePullSecrets:
        - name: docker-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: bellagio
spec:
  type: ClusterIP
  selector:
    component: bellagio
  ports:
    - port: 7000
      targetPort: 7000
