apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuron
spec:
  replicas: 1
  selector:
    matchLabels:
      component: neuron
  template:
    metadata:
      labels:
        component: neuron
    spec:
      containers:
        - name: neuron
          image: matthewli1409/khan-neuron
          imagePullPolicy: Always
          ports:
            - containerPort: 7004
          envFrom:
            - secretRef:
                name: credentials
            - configMapRef:
                name: mm-configmap
      imagePullSecrets:
        - name: dockersecret
---
apiVersion: v1
kind: Service
metadata:
  name: neuron
spec:
  type: ClusterIP
  selector:
    component: neuron
  ports:
    - port: 7004
      targetPort: 7004
